### ISSUE TITLE
Put compiled stylesheet into .gitignore

### ISSUE THREAD

**Issue by Cleop** [charterindex/application#52]
@nelsonic mentioned: https://github.com/charterindex/application/pull/48#pullrequestreview-107978773 that we don't need to keep on adding the compiled stylesheet to version control as it's generated automatically.

- [x] Add style.min.css to .gitignore

**Comment by SimonLab** [comment]
see my thought on this here: https://github.com/charterindex/application/pull/48#discussion_r178009969

I don't think at this stage we can add the file to .gitignore as we need the server on Heroku to be able to access it. So it needs to be on github when we deploy.

**Comment by nelsonic** [comment]
@SimonLab can we not make our "**start script**" in our Heroku `Procfile`:
```
web: npm run css-compile && npm start
``` 

***OR***
in the `package.json` have:
```js
{
  "scripts": [ 
     "app": "node ./bin/www",
     "css-compile": "postcss etc.",
     "start": "npm run css-compile && npm run app"
  ]
}
```

(_I'm trying to avoid having compiled files - which change a lot - in version control_) 
See point 8 in this list: https://www.troyhunt.com/10-commandments-of-good-source-control

It's "fine" to have compiled files in Git at the _start_ of a project because there aren't that many "conflicting" changes, but as soon as more than one person works on something in CSS the `merge-conflicts` become a _major_ waste of time.

`public/stylesheets/style.min.css` is _generated_ by compiling our CSS "source" so it's reproducible.

**Comment by SimonLab** [comment]
I wasn't sure if the generated file would be always available on Horoku:
![image](https://user-images.githubusercontent.com/6057298/38093709-acf88306-3363-11e8-8c0f-f7e1ac351714.png)

But if we generate the file when the server start it should be ok even when we restart the dyno :+1: 
I'll add the file back to .gitignore

**Comment by nelsonic** [comment]
@SimonLab thanks for updating. 👍
